### PR TITLE
Nal dev3

### PR DESCRIPTION
**Pull request by naalong**
Added new tests and corrected others.

### CODE REVIEW

**Comment by mullen2** [comment]
@naalong I got several errors when I tried to run the new tests that you added. I got errors for files not being found, such as basic-demography-bad-rule.ini. Could you please add instructions to  docs/DeveloperGuide.md that describe the steps you need to take to get the new tests you added to work. An external developer should be able to set up and run all the automated tests by following the developer guide.

**Comment by naalong** [comment]
Will do!

**Comment by mullen2** [comment]
@naalong Also, is there a reason that the new tests need to be system tests? If not, then they should be changed to being integration tests for reasons previously discussed.

**Comment by naalong** [comment]
I think it was because I assumed that the RedCap and RedCapProject classes required a connection to a database. I will correct it.

**Comment by mullen2** [comment]
> I think it was because I assumed that the RedCap and RedCapProject classes required a connection to a database. I will correct it.

Thanks! CSV files are an option for loading the extracted and transformed data. CSV files are typically used for the output of integration tests (as defined in the developer guide), because they don't require a database to be set up.

**Pull request merged**
